### PR TITLE
Provide URL to external resources

### PR DESCRIPTION
**Pull request by tferr**
Thought that it would be a good idea to include the API of 3rd -party libraries used by Fiji such as [JFreeChart](http://www.jfree.org/jfreechart/), [Apache Commons](https://commons.apache.org), etc...
The idea is that this would help users interested in scripting those libraries: E.g. [BAR](https://github.com/tferr/Scripts) has a [new example](https://github.com/tferr/Scripts/blob/master/Data_Analysis/Create_Boxplot.bsh) on how to script JFreeChart, but users must find out by themselves how to access its [javadoc](http://www.jfree.org/jfreechart/api/javadoc/). Since BAR [provides links](https://github.com/tferr/Scripts/blob/master/BAR/src/main/java/bar/plugin/Help.java#L201-L209) to the javadoc portal,  including these URLs would make things easier for users. But I will understand if this is considered clutter.

NB: I include resized versions of the [apache-logo](http://www.apache.org/foundation/press/kit/#links), as their policy seems to [allow it](http://www.apache.org/foundation/marks/#guidelines). Could not find information on the remaining libraries, though.

### CODE REVIEW

**Comment by ctrueden** [comment]
Actually, I'd rather integrate these four projects as a new row with `http://javadoc.imagej.net/...` style URLs, just like the others.

Over the years, I have seen many projects break their javadoc URLs—for example, for every release, Apache Pivot puts up a new URL at the new version, and the old URLs go bad, breaking any existing links. The `javadoc.imagej.net` proxies avoid this problem by letting us update everything server side whenever changes are needed, so that all existing links keep working.

**Comment by ctrueden** [comment]
@tferr How is that? OK?

**Comment by tferr** [comment]
More than OK. Perfect! Thanks!
But how did the new URLs got populated? I'm guessing you edited the [Jenkins job](http://jenkins.imagej.net/job/ImageJ-javadoc/)? or it automatically picks the new entries?

**Comment by ctrueden** [comment]
You mean how did I make `http://jenkins.imagej.net/JGraphT/` et. al work?

The current configuration requires to edit the Apache config on the server side. I haven't found an elegant way to put that into version control yet, unfortunately.

**Pull request closed without merging**
